# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpaceX Launches' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpaceX Launches

  pod 'Alamofire', '~> 5.5'
  pod 'Kingfisher', '~> 7.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Reusable'

  target 'SpaceX LaunchesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpaceX LaunchesUITests' do
    # Pods for testing
  end

end
